spring.application.name=ApoloInsightsBackEnd
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Para desenvolvimento coloque "dev"
# Para Produção coloque "prod"
spring.profiles.active=dev