spring.application.name=ApoloInsightsBackEnd
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
api.security.token.secret=${JWT_SECRET:12345678}



# Para desenvolvimento coloque "dev"
# Para Produção coloque "prod"
spring.profiles.active=dev