server.port=8081
spring.datasource.url=jdbc:mysql://meubanco.mysql.database.azure.com:3306/barbearia?ssl-mode=REQUIRED
spring.datasource.username=grupo4
spring.datasource.password=Gr4banco
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

#variaveis:
cors.allowed.origin=http://instancia:3000
api.security.token.expiration-time=2