spring.application.name=ApoloInsightsBackEnd
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
api.security.token.secret=${JWT_SECRET:12345678}

# Para desenvolvimento coloque "dev"
# Para Produ��o coloque "prod"
#
spring.profiles.active=prod

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=studioberthollo@gmail.com
spring.mail.password=aflh hqzx kqdp zdzt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true