server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/apoloInsights
spring.datasource.username=root
spring.datasource.password=xuxuxuxu
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.flyway.enabled=false
#
#variaveis:
springdoc.swagger-ui.path=/docs
spring.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger.ui.defaultModelExpandDepth=1
api.security.token.expiration-time=500
cors.allowed.origin=http://localhost:3000,http://localhost:4200,http://localhost:5173


